name: ${project.name}
main: net.plazmix.practice.PlazmixPracticePlugin
version: ${project.version}
description: ${project.description}
website: ${project.url}

authors: [MasterCapeXD, Desinger]

depend: [PlazmixAPI]
