package net.plazmix.practice.mlgrush.state;

import lombok.NonNull;
import net.plazmix.core.PlazmixCoreApi;
import net.plazmix.game.GamePlugin;
import net.plazmix.game.setting.GameSetting;
import net.plazmix.game.state.type.StandardWaitingState;
import net.plazmix.game.utility.GameSchedulers;
import net.plazmix.game.utility.hotbar.GameHotbar;
import net.plazmix.game.utility.hotbar.GameHotbarBuilder;
import net.plazmix.practice.mlgrush.scoreboard.MlgrushWaitingScoreboard;
import net.plazmix.practice.mlgrush.util.BedAmountSelectInventory;
import net.plazmix.practice.mlgrush.util.MlgrushGameConstants;
import net.plazmix.practice.util.GeneralGameConstants;
import net.plazmix.utility.ItemUtil;
import net.plazmix.utility.player.PlazmixUser;
import org.bukkit.Bukkit;
import org.bukkit.Location;
import org.bukkit.Material;
import org.bukkit.event.player.PlayerJoinEvent;
import org.bukkit.event.player.PlayerQuitEvent;

public class MlgrushWaitingState extends StandardWaitingState {

    private final GameHotbar gameHotbar = GameHotbarBuilder.newBuilder()
            .setMoveItems(false)

            .addItem(1, ItemUtil.newBuilder(Material.BED)
                            .setName("§aВыбор кроватей")
                            .build(),

                    player -> new BedAmountSelectInventory().openInventory(player))

            .addItem(5, ItemUtil.newBuilder(Material.CHEST)
                            .setName("§aМагазин")
                            .build(),

                    player -> plugin.getService().createCategoriesAutoGeneratedMenu(5, "Магазин").openInventory(player))

            .addItem(9, ItemUtil.newBuilder(Material.MAGMA_CREAM)
                            .setName("§aПокинуть арену")
                            .build(),

                    PlazmixCoreApi::redirectToLobby)

            .build();

    public MlgrushWaitingState(GamePlugin plugin) {
        super(plugin, "Ожидание игроков");
    }

    @Override
    protected void onStart() {
        GameSetting.setAll(plugin.getService(), false);
    }

    @Override
    protected Location getTeleportLocation() {
        return GeneralGameConstants.LOBBY_LOCATION;
    }

    @Override
    protected void handleEvent(@NonNull PlayerJoinEvent event) {
        int online = Bukkit.getOnlinePlayers().size();
        int maxOnline = getPlugin().getService().getMaxPlayers();
        if(online > maxOnline)
            PlazmixCoreApi.redirectToLobby(event.getPlayer());

        // В шедулере, потому что баккит так хочет :(
        GameSchedulers.runLater(10, () -> {

            new MlgrushWaitingScoreboard(getTimerStatus(), event.getPlayer());

            gameHotbar.setHotbarTo(event.getPlayer());
        });

        event.setJoinMessage(MlgrushGameConstants.PREFIX + PlazmixUser.of(event.getPlayer()).getDisplayName() + " §fподключился к игре! §7(" + online + "/" + maxOnline + ")");

        // Если сервер полный, то запускаем таймер
        if (online >= maxOnline && !timerStatus.isLived()) {
            timerStatus.runTask(5);
        }
    }

    @Override
    protected void handleEvent(@NonNull PlayerQuitEvent event) {
        int online = Bukkit.getOnlinePlayers().size() - 1;
        int maxOnline = getPlugin().getService().getMaxPlayers();

        event.setQuitMessage(MlgrushGameConstants.PREFIX + PlazmixUser.of(event.getPlayer()).getDisplayName() + " §fпокинул игру! §7(" + online + "/" + maxOnline + ")");

        // Если кто-то вышел, то надо вырубать таймер
        if (online < maxOnline && timerStatus.isLived()) {
            timerStatus.cancelTask();
        }
    }

    @Override
    protected void handleTimerUpdate(@NonNull TimerStatus timerStatus) {
    }

}
